# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-14 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=14)),
                ('email', models.CharField(max_length=14)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
