# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-14 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biom', '0004_sample_model_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='model_pic',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
