# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-14 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biom', '0005_auto_20190114_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='model_pic',
            field=models.FileField(upload_to='img/'),
        ),
    ]
