# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-14 11:08
from __future__ import unicode_literals

import biom.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biom', '0006_auto_20190114_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='model_pic',
            field=models.FileField(upload_to=biom.models.user_directory_path),
        ),
    ]
