# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-14 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biom', '0008_auto_20190114_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_panel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=14)),
                ('passkey', models.CharField(max_length=14)),
            ],
        ),
    ]
