# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-14 18:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biom', '0009_admin_panel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin_panel',
            old_name='name',
            new_name='name1',
        ),
        migrations.RenameField(
            model_name='admin_panel',
            old_name='passkey',
            new_name='passkey1',
        ),
    ]
